// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MvcBook.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinEdit uILoginEdit = this.UIHomePageProjectMozilWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIUsernameEdit = this.UIHomePageProjectMozilWindow.UILoginProjectDocument.UIUsernameEdit;
            WinListItem uIAdminListItem = this.UIItemWindow.UIItemList.UIAdminListItem;
            WinCustom uIItemCustom = this.UIHomePageProjectMozilWindow.UIItemCustom;
            WinEdit uIPasswordEdit = this.UIHomePageProjectMozilWindow.UILoginProjectDocument.UIPasswordEdit;
            WinButton uILoginButton = this.UIHomePageProjectMozilWindow.UILoginProjectDocument.UILoginButton;
            WinCustom uIItemCustom1 = this.UIHomePageProjectMozilWindow.UIHomePageProjectDocument.UIItemCustom;
            WinEdit uIBooksEdit = this.UIHomePageProjectMozilWindow.UIBooksHyperlink.UIBooksEdit;
            WinEdit uIEditEdit = this.UIHomePageProjectMozilWindow.UIEditHyperlink.UIEditEdit;
            WinComboBox uIAuthorIDComboBox = this.UIHomePageProjectMozilWindow.UIEditProjectDocument.UIAuthorIDComboBox;
            WinComboBox uIAuthorIDComboBox1 = this.UIItemWindow1.UIAuthorIDComboBox;
            WinButton uISaveButton = this.UIHomePageProjectMozilWindow.UIEditProjectDocument.UISaveButton;
            #endregion

            // Click 'Log in' text box
            Mouse.Click(uILoginEdit, new Point(14, 6));

            // Type 'ad' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod1Params.UIUsernameEditText;

            // Click 'admin' list item
            Mouse.Click(uIAdminListItem, new Point(81, 7));

            // Double-Click custom control
            Mouse.DoubleClick(uIItemCustom, new Point(212, 104));

            // Double-Click custom control
            Mouse.DoubleClick(uIItemCustom, new Point(212, 104));

            // Double-Click custom control
            Mouse.DoubleClick(uIItemCustom, new Point(212, 104));

            // Double-Click custom control
            Mouse.DoubleClick(uIItemCustom, new Point(212, 104));

            // Click 'Password' text box
            Mouse.Click(uIPasswordEdit, new Point(58, 14));

            // Click 'Password' text box
            Mouse.Click(uIPasswordEdit, new Point(58, 14));

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.RecordedMethod1Params.UIPasswordEditSendKeys, true);

            // Last mouse action was not recorded.

            // Click 'Log in' text box
            Mouse.Click(uILoginEdit, new Point(25, 11));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod1Params.UIUsernameEditText1;

            // Click 'Password' text box
            Mouse.Click(uIPasswordEdit, new Point(98, 19));

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.RecordedMethod1Params.UIPasswordEditSendKeys1, true);

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(32, 30));

            // Click custom control numbered 2 in 'Home Page - Project' document
            Mouse.Click(uIItemCustom1, new Point(311, 24));

            // Click 'Books' text box
            Mouse.Click(uIBooksEdit, new Point(27, 7));

            // Click 'Edit' text box
            Mouse.Click(uIEditEdit, new Point(8, 15));

            // Click 'AuthorID' combo box
            Mouse.Click(uIAuthorIDComboBox, new Point(104, 13));

            // Click 'AuthorID' combo box
            Mouse.Click(uIAuthorIDComboBox1, new Point(85, 45));

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(22, 22));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinHyperlink uICreateNewHyperlink = this.UIHomePageProjectMozilWindow.UIIndexProjectDocument.UICreateNewHyperlink;
            WinEdit uITitleEdit = this.UIHomePageProjectMozilWindow.UICreateProjectDocument.UITitleEdit;
            WinEdit uIReleaseDateEdit = this.UIHomePageProjectMozilWindow.UICreateProjectDocument.UIReleaseDateEdit;
            WinEdit uIGenreEdit = this.UIHomePageProjectMozilWindow.UICreateProjectDocument.UIGenreEdit;
            WinButton uICreateButton = this.UIHomePageProjectMozilWindow.UICreateProjectDocument.UICreateButton;
            WinEdit uIItem4Edit = this.UIHomePageProjectMozilWindow.UIItem4Hyperlink.UIItem4Edit;
            WinEdit uIDeleteEdit = this.UIHomePageProjectMozilWindow.UIDeleteHyperlink.UIDeleteEdit;
            WinButton uIDeleteButton = this.UIHomePageProjectMozilWindow.UIDeleteProjectDocument.UIDeleteButton;
            #endregion

            // Click 'Create New' link
            Mouse.Click(uICreateNewHyperlink, new Point(58, 30));

            // Type 'Ksi' in 'Title' text box
            uITitleEdit.Text = this.RecordedMethod2Params.UITitleEditText;

            // Type 'Alt, Control + a' in 'Title' text box
            Keyboard.SendKeys(uITitleEdit, this.RecordedMethod2Params.UITitleEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'Ksią' in 'Title' text box
            uITitleEdit.Text = this.RecordedMethod2Params.UITitleEditText1;

            // Type 'Alt, Control + z' in 'Title' text box
            Keyboard.SendKeys(uITitleEdit, this.RecordedMethod2Params.UITitleEditSendKeys1, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'Książka' in 'Title' text box
            uITitleEdit.Text = this.RecordedMethod2Params.UITitleEditText2;

            // Type '19/10/2015' in 'Release Date' text box
            uIReleaseDateEdit.Text = this.RecordedMethod2Params.UIReleaseDateEditText;

            // Type 'Comedy' in 'Genre' text box
            uIGenreEdit.Text = this.RecordedMethod2Params.UIGenreEditText;

            // Click 'Create' button
            Mouse.Click(uICreateButton, new Point(45, 10));

            // Click '4' text box
            Mouse.Click(uIItem4Edit, new Point(6, 5));

            // Click 'Delete' text box
            Mouse.Click(uIDeleteEdit, new Point(21, 13));

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(21, 6));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UIHomePageProjectMozilWindow UIHomePageProjectMozilWindow
        {
            get
            {
                if ((this.mUIHomePageProjectMozilWindow == null))
                {
                    this.mUIHomePageProjectMozilWindow = new UIHomePageProjectMozilWindow();
                }
                return this.mUIHomePageProjectMozilWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1();
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UIHomePageProjectMozilWindow mUIHomePageProjectMozilWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'ad' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "ad";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "I5MQfG2n7aOG6eSvpY3eTt+yoASAvJSS";
        
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText1 = "admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys1 = "I5MQfG2n7aOG6eSvpY3eTt+yoASAvJSS";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Ksi' in 'Title' text box
        /// </summary>
        public string UITitleEditText = "Ksi";
        
        /// <summary>
        /// Type 'Alt, Control + a' in 'Title' text box
        /// </summary>
        public string UITitleEditSendKeys = "a";
        
        /// <summary>
        /// Type 'Ksią' in 'Title' text box
        /// </summary>
        public string UITitleEditText1 = "Ksią";
        
        /// <summary>
        /// Type 'Alt, Control + z' in 'Title' text box
        /// </summary>
        public string UITitleEditSendKeys1 = "z";
        
        /// <summary>
        /// Type 'Książka' in 'Title' text box
        /// </summary>
        public string UITitleEditText2 = "Książka";
        
        /// <summary>
        /// Type '19/10/2015' in 'Release Date' text box
        /// </summary>
        public string UIReleaseDateEditText = "19/10/2015";
        
        /// <summary>
        /// Type 'Comedy' in 'Genre' text box
        /// </summary>
        public string UIGenreEditText = "Comedy";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageProjectMozilWindow : WinWindow
    {
        
        public UIHomePageProjectMozilWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - Project - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
            this.WindowTitles.Add("Log in - Project - Mozilla Firefox");
            this.WindowTitles.Add("Index - Project - Mozilla Firefox");
            this.WindowTitles.Add("Edit - Project - Mozilla Firefox");
            this.WindowTitles.Add("Create - Project - Mozilla Firefox");
            this.WindowTitles.Add("Delete - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UILoginHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new UILoginHyperlink(this);
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public UILoginProjectDocument UILoginProjectDocument
        {
            get
            {
                if ((this.mUILoginProjectDocument == null))
                {
                    this.mUILoginProjectDocument = new UILoginProjectDocument(this);
                }
                return this.mUILoginProjectDocument;
            }
        }
        
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Log in - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIHomePageProjectDocument UIHomePageProjectDocument
        {
            get
            {
                if ((this.mUIHomePageProjectDocument == null))
                {
                    this.mUIHomePageProjectDocument = new UIHomePageProjectDocument(this);
                }
                return this.mUIHomePageProjectDocument;
            }
        }
        
        public UIBooksHyperlink UIBooksHyperlink
        {
            get
            {
                if ((this.mUIBooksHyperlink == null))
                {
                    this.mUIBooksHyperlink = new UIBooksHyperlink(this);
                }
                return this.mUIBooksHyperlink;
            }
        }
        
        public UIEditHyperlink UIEditHyperlink
        {
            get
            {
                if ((this.mUIEditHyperlink == null))
                {
                    this.mUIEditHyperlink = new UIEditHyperlink(this);
                }
                return this.mUIEditHyperlink;
            }
        }
        
        public UIEditProjectDocument UIEditProjectDocument
        {
            get
            {
                if ((this.mUIEditProjectDocument == null))
                {
                    this.mUIEditProjectDocument = new UIEditProjectDocument(this);
                }
                return this.mUIEditProjectDocument;
            }
        }
        
        public UIIndexProjectDocument UIIndexProjectDocument
        {
            get
            {
                if ((this.mUIIndexProjectDocument == null))
                {
                    this.mUIIndexProjectDocument = new UIIndexProjectDocument(this);
                }
                return this.mUIIndexProjectDocument;
            }
        }
        
        public UICreateProjectDocument UICreateProjectDocument
        {
            get
            {
                if ((this.mUICreateProjectDocument == null))
                {
                    this.mUICreateProjectDocument = new UICreateProjectDocument(this);
                }
                return this.mUICreateProjectDocument;
            }
        }
        
        public UIItem4Hyperlink UIItem4Hyperlink
        {
            get
            {
                if ((this.mUIItem4Hyperlink == null))
                {
                    this.mUIItem4Hyperlink = new UIItem4Hyperlink(this);
                }
                return this.mUIItem4Hyperlink;
            }
        }
        
        public UIDeleteHyperlink UIDeleteHyperlink
        {
            get
            {
                if ((this.mUIDeleteHyperlink == null))
                {
                    this.mUIDeleteHyperlink = new UIDeleteHyperlink(this);
                }
                return this.mUIDeleteHyperlink;
            }
        }
        
        public UIDeleteProjectDocument UIDeleteProjectDocument
        {
            get
            {
                if ((this.mUIDeleteProjectDocument == null))
                {
                    this.mUIDeleteProjectDocument = new UIDeleteProjectDocument(this);
                }
                return this.mUIDeleteProjectDocument;
            }
        }
        #endregion
        
        #region Fields
        private UILoginHyperlink mUILoginHyperlink;
        
        private UILoginProjectDocument mUILoginProjectDocument;
        
        private WinCustom mUIItemCustom;
        
        private UIHomePageProjectDocument mUIHomePageProjectDocument;
        
        private UIBooksHyperlink mUIBooksHyperlink;
        
        private UIEditHyperlink mUIEditHyperlink;
        
        private UIEditProjectDocument mUIEditProjectDocument;
        
        private UIIndexProjectDocument mUIIndexProjectDocument;
        
        private UICreateProjectDocument mUICreateProjectDocument;
        
        private UIItem4Hyperlink mUIItem4Hyperlink;
        
        private UIDeleteHyperlink mUIDeleteHyperlink;
        
        private UIDeleteProjectDocument mUIDeleteProjectDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginHyperlink : WinHyperlink
    {
        
        public UILoginHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Log in";
            this.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Log in";
                    this.mUILoginEdit.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILoginEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginProjectDocument : WinControl
    {
        
        public UILoginProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Log in - Project";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Log in - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "User name";
                    this.mUIUsernameEdit.WindowTitles.Add("Log in - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WinEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Log in - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WinButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WinButton.PropertyNames.Name] = "Log in";
                    this.mUILoginButton.WindowTitles.Add("Log in - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIUsernameEdit;
        
        private WinEdit mUIPasswordEdit;
        
        private WinButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageProjectDocument : WinControl
    {
        
        public UIHomePageProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - Project";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["Instance"] = "2";
                    this.mUIItemCustom.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBooksHyperlink : WinHyperlink
    {
        
        public UIBooksHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Books";
            this.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIBooksEdit
        {
            get
            {
                if ((this.mUIBooksEdit == null))
                {
                    this.mUIBooksEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIBooksEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Books";
                    this.mUIBooksEdit.WindowTitles.Add("Home Page - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIBooksEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIBooksEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEditHyperlink : WinHyperlink
    {
        
        public UIEditHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Edit";
            this.WindowTitles.Add("Index - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIEditEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Edit";
                    this.mUIEditEdit.WindowTitles.Add("Index - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEditProjectDocument : WinControl
    {
        
        public UIEditProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Edit - Project";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Edit - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIAuthorIDComboBox
        {
            get
            {
                if ((this.mUIAuthorIDComboBox == null))
                {
                    this.mUIAuthorIDComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIAuthorIDComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "AuthorID";
                    this.mUIAuthorIDComboBox.WindowTitles.Add("Edit - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIAuthorIDComboBox;
            }
        }
        
        public WinButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[WinButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.WindowTitles.Add("Edit - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIAuthorIDComboBox;
        
        private WinButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexProjectDocument : WinControl
    {
        
        public UIIndexProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Index - Project";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Index - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UICreateNewHyperlink
        {
            get
            {
                if ((this.mUICreateNewHyperlink == null))
                {
                    this.mUICreateNewHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUICreateNewHyperlink.SearchProperties[WinHyperlink.PropertyNames.Name] = "Create New";
                    this.mUICreateNewHyperlink.WindowTitles.Add("Index - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUICreateNewHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUICreateNewHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateProjectDocument : WinControl
    {
        
        public UICreateProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Create - Project";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Create - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UITitleEdit
        {
            get
            {
                if ((this.mUITitleEdit == null))
                {
                    this.mUITitleEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITitleEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Title";
                    this.mUITitleEdit.WindowTitles.Add("Create - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUITitleEdit;
            }
        }
        
        public WinEdit UIReleaseDateEdit
        {
            get
            {
                if ((this.mUIReleaseDateEdit == null))
                {
                    this.mUIReleaseDateEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIReleaseDateEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Release Date";
                    this.mUIReleaseDateEdit.WindowTitles.Add("Create - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIReleaseDateEdit;
            }
        }
        
        public WinEdit UIGenreEdit
        {
            get
            {
                if ((this.mUIGenreEdit == null))
                {
                    this.mUIGenreEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIGenreEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Genre";
                    this.mUIGenreEdit.WindowTitles.Add("Create - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIGenreEdit;
            }
        }
        
        public WinButton UICreateButton
        {
            get
            {
                if ((this.mUICreateButton == null))
                {
                    this.mUICreateButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICreateButton.SearchProperties[WinButton.PropertyNames.Name] = "Create";
                    this.mUICreateButton.WindowTitles.Add("Create - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUICreateButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITitleEdit;
        
        private WinEdit mUIReleaseDateEdit;
        
        private WinEdit mUIGenreEdit;
        
        private WinButton mUICreateButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem4Hyperlink : WinHyperlink
    {
        
        public UIItem4Hyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "4";
            this.WindowTitles.Add("Index - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItem4Edit
        {
            get
            {
                if ((this.mUIItem4Edit == null))
                {
                    this.mUIItem4Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItem4Edit.SearchProperties[WinEdit.PropertyNames.Name] = "4";
                    this.mUIItem4Edit.WindowTitles.Add("Index - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItem4Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItem4Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDeleteHyperlink : WinHyperlink
    {
        
        public UIDeleteHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Delete";
            this.WindowTitles.Add("Index - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIDeleteEdit
        {
            get
            {
                if ((this.mUIDeleteEdit == null))
                {
                    this.mUIDeleteEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIDeleteEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Delete";
                    this.mUIDeleteEdit.WindowTitles.Add("Index - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIDeleteEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIDeleteEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDeleteProjectDocument : WinControl
    {
        
        public UIDeleteProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Delete - Project";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Delete - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete";
                    this.mUIDeleteButton.WindowTitles.Add("Delete - Project - Mozilla Firefox");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Pulpit";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Log in - Project - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinListItem UIAdminListItem
        {
            get
            {
                if ((this.mUIAdminListItem == null))
                {
                    this.mUIAdminListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIAdminListItem.SearchProperties[WinListItem.PropertyNames.Name] = "admin";
                    #endregion
                }
                return this.mUIAdminListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIAdminListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "AuthorID";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            #endregion
        }
        
        #region Properties
        public WinComboBox UIAuthorIDComboBox
        {
            get
            {
                if ((this.mUIAuthorIDComboBox == null))
                {
                    this.mUIAuthorIDComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIAuthorIDComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "AuthorID";
                    #endregion
                }
                return this.mUIAuthorIDComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIAuthorIDComboBox;
        #endregion
    }
}
