// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AddNewBook - Use 'AddNewBookParams' to pass parameters into this method.
        /// </summary>
        public void AddNewBook()
        {
            #region Variable Declarations
            HtmlHyperlink uICreateNewHyperlink = this.UIHomePageProjectInterWindow.UIIndexProjectDocument.UICreateNewHyperlink;
            HtmlEdit uITitleEdit = this.UIHomePageProjectInterWindow.UICreateProjectDocument.UITitleEdit;
            HtmlEdit uIReleaseDateEdit = this.UIHomePageProjectInterWindow.UICreateProjectDocument.UIReleaseDateEdit;
            HtmlEdit uIGenreEdit = this.UIHomePageProjectInterWindow.UICreateProjectDocument.UIGenreEdit;
            HtmlInputButton uICreateButton = this.UIHomePageProjectInterWindow.UICreateProjectDocument.UICreateButton;
            HtmlComboBox uIBookGenreComboBox = this.UIHomePageProjectInterWindow.UIIndexProjectDocument.UIBookGenreComboBox;
            HtmlInputButton uIFilterButton = this.UIHomePageProjectInterWindow.UIIndexProjectDocument.UIFilterButton;
            HtmlHyperlink uIItem2Hyperlink = this.UIHomePageProjectInterWindow.UIIndexProjectDocument2.UIItem2Hyperlink;
            #endregion

            // Click 'Create New' link
            Mouse.Click(uICreateNewHyperlink, new Point(62, 19));

            // Type 'New' in 'Title' text box
            uITitleEdit.Text = this.AddNewBookParams.UITitleEditText;

            // Type '19/10/2015' in 'Release Date' text box
            uIReleaseDateEdit.Text = this.AddNewBookParams.UIReleaseDateEditText;

            // Type 'Thriller' in 'Genre' text box
            uIGenreEdit.Text = this.AddNewBookParams.UIGenreEditText;

            // Click 'Create' button
            Mouse.Click(uICreateButton, new Point(33, 13));

            // Select 'Thriller' in 'bookGenre' combo box
            uIBookGenreComboBox.SelectedItem = this.AddNewBookParams.UIBookGenreComboBoxSelectedItem;

            // Click 'Filter' button
            Mouse.Click(uIFilterButton, new Point(19, 31));

            // Click '2' link
            Mouse.Click(uIItem2Hyperlink, new Point(18, 16));
        }
        
        /// <summary>
        /// AssertError - Use 'AssertErrorExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertError()
        {
            #region Variable Declarations
            HtmlCustom uIInvalidusernameorpasCustom = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UILoginFormCustom.UIInvalidusernameorpasCustom;
            #endregion

            // Verify that the 'InnerText' property of 'Invalid username or password.' custom control equals 'Invalid username or password.'
            Assert.AreEqual(this.AssertErrorExpectedValues.UIInvalidusernameorpasCustomInnerText, uIInvalidusernameorpasCustom.InnerText);
        }
        
        /// <summary>
        /// AssertHello - Use 'AssertHelloExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertHello()
        {
            #region Variable Declarations
            HtmlHyperlink uIHelloAdminHyperlink = this.UIHomePageProjectInterWindow.UIHomePageProjectDocument.UILogoutFormCustom.UIHelloAdminHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Hello Admin!' link equals 'Hello Admin!'
            Assert.AreEqual(this.AssertHelloExpectedValues.UIHelloAdminHyperlinkInnerText, uIHelloAdminHyperlink.InnerText);
        }
        
        /// <summary>
        /// AssertTextDelete - Use 'AssertTextDeleteExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertTextDelete()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIHomePageProjectInterWindow.UIDeleteProjectDocument.UIItemCustom;
            #endregion

            // Verify that the 'InnerText' property of custom control equals 'Delete'
            Assert.AreEqual(this.AssertTextDeleteExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText);
        }
        
        /// <summary>
        /// AssertTitle - Use 'AssertTitleExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertTitle()
        {
            #region Variable Declarations
            HtmlCell uINewCell = this.UIHomePageProjectInterWindow.UIIndexProjectDocument1.UIItemTable.UINewCell;
            #endregion

            // Verify that the 'InnerText' property of 'New' cell equals 'New '
            Assert.AreEqual(this.AssertTitleExpectedValues.UINewCellInnerText, uINewCell.InnerText);
        }
        
        /// <summary>
        /// AssertTitleDetails - Use 'AssertTitleDetailsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertTitleDetails()
        {
            #region Variable Declarations
            HtmlCustom uITheDaVinciCodeCustom = this.UIHomePageProjectInterWindow.UIDetailsProjectDocument1.UITheDaVinciCodeCustom;
            #endregion

            // Verify that the 'InnerText' property of 'The Da Vinci Code' custom control equals 'The Da Vinci Code '
            Assert.AreEqual(this.AssertTitleDetailsExpectedValues.UITheDaVinciCodeCustomInnerText, uITheDaVinciCodeCustom.InnerText);
        }
        
        /// <summary>
        /// ClickBooks
        /// </summary>
        public void ClickBooks()
        {
            #region Variable Declarations
            HtmlHyperlink uIBooksHyperlink = this.UIHomePageProjectInterWindow.UIHomePageProjectDocument.UIBooksHyperlink;
            #endregion

            // Click 'Books' link
            Mouse.Click(uIBooksHyperlink, new Point(42, 33));
        }
        
        /// <summary>
        /// ClickDelete
        /// </summary>
        public void ClickDelete()
        {
            #region Variable Declarations
            HtmlHyperlink uIItem3Hyperlink = this.UIHomePageProjectInterWindow.UIIndexProjectDocument.UIItem3Hyperlink;
            HtmlHyperlink uIDeleteHyperlink = this.UIHomePageProjectInterWindow.UIIndexProjectDocument11.UIDeleteHyperlink;
            #endregion

            // Click '3' link
            Mouse.Click(uIItem3Hyperlink, new Point(18, 16));

            // Click 'Delete' link
            Mouse.Click(uIDeleteHyperlink, new Point(34, 18));
        }
        
        /// <summary>
        /// ClickDetails
        /// </summary>
        public void ClickDetails()
        {
            #region Variable Declarations
            HtmlHyperlink uIDetailsHyperlink = this.UIHomePageProjectInterWindow.UIIndexProjectDocument.UIDetailsHyperlink;
            #endregion

            // Click 'Details' link
            Mouse.Click(uIDetailsHyperlink, new Point(27, 21));
        }
        
        /// <summary>
        /// LoginAsAdmin - Use 'LoginAsAdminParams' to pass parameters into this method.
        /// </summary>
        public void LoginAsAdmin()
        {
            #region Variable Declarations
            HtmlHyperlink uILoginHyperlink = this.UIHomePageProjectInterWindow.UIHomePageProjectDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UILoginFormCustom.UILoginButton;
            #endregion

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(34, 29));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.LoginAsAdminParams.UIUsernameEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LoginAsAdminParams.UIPasswordEditPassword;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(36, 14));
        }
        
        /// <summary>
        /// LogOff
        /// </summary>
        public void LogOff()
        {
            #region Variable Declarations
            HtmlHyperlink uILogoffHyperlink = this.UIHomePageProjectInterWindow.UIHomePageProjectDocument.UILogoutFormCustom.UILogoffHyperlink;
            #endregion

            // Click 'Log off' link
            Mouse.Click(uILogoffHyperlink, new Point(45, 24));
        }
        
        /// <summary>
        /// StartBrowser - Use 'StartBrowserParams' to pass parameters into this method.
        /// </summary>
        public void StartBrowser()
        {
            #region Variable Declarations
            WinEdit uIAdresiwyszukiwaniezaEdit = this.UINowakartaInternetExpWindow.UIPasekadresuClient.UIAdresiwyszukiwaniezaEdit;
            WinEdit uIItemEdit = this.UINowakartaInternetExpWindow.UIItemWindow.UIItemEdit;
            WinButton uIPrzejdźdohttplocalhoButton = this.UINowakartaInternetExpWindow.UIKontrolkastronyToolBar.UIPrzejdźdohttplocalhoButton;
            #endregion

            // Go to web page 'about:Tabs' using new browser instance
            this.UINowakartaInternetExpWindow.LaunchUrl(new System.Uri(this.StartBrowserParams.UINowakartaInternetExpWindowUrl));

            // Click 'Adres i wyszukiwanie za pomocą Bing' text box
            Mouse.Click(uIAdresiwyszukiwaniezaEdit, new Point(122, 13));

            // Type 'http{RShiftKey}:/l{Back}//{Back}local' in text box
            Keyboard.SendKeys(uIItemEdit, this.StartBrowserParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type 'host{RShiftKey}:63352' in text box
            Keyboard.SendKeys(uIItemEdit, this.StartBrowserParams.UIItemEditSendKeys1, ModifierKeys.None);

            // Click 'Przejdź do „http://localhost:63352/” (Alt+Enter, a...' button
            Mouse.Click(uIPrzejdźdohttplocalhoButton, new Point(6, 12));
        }
        
        /// <summary>
        /// BadLogin - Use 'BadLoginParams' to pass parameters into this method.
        /// </summary>
        public void BadLogin()
        {
            #region Variable Declarations
            HtmlHyperlink uILoginHyperlink = this.UIHomePageProjectInterWindow.UIHomePageProjectDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIHomePageProjectInterWindow.UILoginProjectDocument.UILoginFormCustom.UILoginButton;
            #endregion

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(41, 27));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.BadLoginParams.UIUsernameEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.BadLoginParams.UIPasswordEditPassword;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(45, 13));
        }
        
        #region Properties
        public virtual AddNewBookParams AddNewBookParams
        {
            get
            {
                if ((this.mAddNewBookParams == null))
                {
                    this.mAddNewBookParams = new AddNewBookParams();
                }
                return this.mAddNewBookParams;
            }
        }
        
        public virtual AssertErrorExpectedValues AssertErrorExpectedValues
        {
            get
            {
                if ((this.mAssertErrorExpectedValues == null))
                {
                    this.mAssertErrorExpectedValues = new AssertErrorExpectedValues();
                }
                return this.mAssertErrorExpectedValues;
            }
        }
        
        public virtual AssertHelloExpectedValues AssertHelloExpectedValues
        {
            get
            {
                if ((this.mAssertHelloExpectedValues == null))
                {
                    this.mAssertHelloExpectedValues = new AssertHelloExpectedValues();
                }
                return this.mAssertHelloExpectedValues;
            }
        }
        
        public virtual AssertTextDeleteExpectedValues AssertTextDeleteExpectedValues
        {
            get
            {
                if ((this.mAssertTextDeleteExpectedValues == null))
                {
                    this.mAssertTextDeleteExpectedValues = new AssertTextDeleteExpectedValues();
                }
                return this.mAssertTextDeleteExpectedValues;
            }
        }
        
        public virtual AssertTitleExpectedValues AssertTitleExpectedValues
        {
            get
            {
                if ((this.mAssertTitleExpectedValues == null))
                {
                    this.mAssertTitleExpectedValues = new AssertTitleExpectedValues();
                }
                return this.mAssertTitleExpectedValues;
            }
        }
        
        public virtual AssertTitleDetailsExpectedValues AssertTitleDetailsExpectedValues
        {
            get
            {
                if ((this.mAssertTitleDetailsExpectedValues == null))
                {
                    this.mAssertTitleDetailsExpectedValues = new AssertTitleDetailsExpectedValues();
                }
                return this.mAssertTitleDetailsExpectedValues;
            }
        }
        
        public virtual LoginAsAdminParams LoginAsAdminParams
        {
            get
            {
                if ((this.mLoginAsAdminParams == null))
                {
                    this.mLoginAsAdminParams = new LoginAsAdminParams();
                }
                return this.mLoginAsAdminParams;
            }
        }
        
        public virtual StartBrowserParams StartBrowserParams
        {
            get
            {
                if ((this.mStartBrowserParams == null))
                {
                    this.mStartBrowserParams = new StartBrowserParams();
                }
                return this.mStartBrowserParams;
            }
        }
        
        public virtual BadLoginParams BadLoginParams
        {
            get
            {
                if ((this.mBadLoginParams == null))
                {
                    this.mBadLoginParams = new BadLoginParams();
                }
                return this.mBadLoginParams;
            }
        }
        
        public UINowakartaInternetExpWindow UINowakartaInternetExpWindow
        {
            get
            {
                if ((this.mUINowakartaInternetExpWindow == null))
                {
                    this.mUINowakartaInternetExpWindow = new UINowakartaInternetExpWindow();
                }
                return this.mUINowakartaInternetExpWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIHomePageProjectInterWindow UIHomePageProjectInterWindow
        {
            get
            {
                if ((this.mUIHomePageProjectInterWindow == null))
                {
                    this.mUIHomePageProjectInterWindow = new UIHomePageProjectInterWindow();
                }
                return this.mUIHomePageProjectInterWindow;
            }
        }
        #endregion
        
        #region Fields
        private AddNewBookParams mAddNewBookParams;
        
        private AssertErrorExpectedValues mAssertErrorExpectedValues;
        
        private AssertHelloExpectedValues mAssertHelloExpectedValues;
        
        private AssertTextDeleteExpectedValues mAssertTextDeleteExpectedValues;
        
        private AssertTitleExpectedValues mAssertTitleExpectedValues;
        
        private AssertTitleDetailsExpectedValues mAssertTitleDetailsExpectedValues;
        
        private LoginAsAdminParams mLoginAsAdminParams;
        
        private StartBrowserParams mStartBrowserParams;
        
        private BadLoginParams mBadLoginParams;
        
        private UINowakartaInternetExpWindow mUINowakartaInternetExpWindow;
        
        private UIItemWindow1 mUIItemWindow;
        
        private UIHomePageProjectInterWindow mUIHomePageProjectInterWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddNewBook'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AddNewBookParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'New' in 'Title' text box
        /// </summary>
        public string UITitleEditText = "New";
        
        /// <summary>
        /// Type '19/10/2015' in 'Release Date' text box
        /// </summary>
        public string UIReleaseDateEditText = "19/10/2015";
        
        /// <summary>
        /// Type 'Thriller' in 'Genre' text box
        /// </summary>
        public string UIGenreEditText = "Thriller";
        
        /// <summary>
        /// Select 'Thriller' in 'bookGenre' combo box
        /// </summary>
        public string UIBookGenreComboBoxSelectedItem = "Thriller";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertError'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertErrorExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Invalid username or password.' custom control equals 'Invalid username or password.'
        /// </summary>
        public string UIInvalidusernameorpasCustomInnerText = "Invalid username or password.";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertHello'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertHelloExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Hello Admin!' link equals 'Hello Admin!'
        /// </summary>
        public string UIHelloAdminHyperlinkInnerText = "Hello Admin!";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertTextDelete'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertTextDeleteExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'Delete'
        /// </summary>
        public string UIItemCustomInnerText = "Delete";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertTitle'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertTitleExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'New' cell equals 'New '
        /// </summary>
        public string UINewCellInnerText = "New ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertTitleDetails'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertTitleDetailsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'The Da Vinci Code' custom control equals 'The Da Vinci Code '
        /// </summary>
        public string UITheDaVinciCodeCustomInnerText = "The Da Vinci Code ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginAsAdmin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginAsAdminParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "I5MQfG2n7aOG6eSvpY3eTt+yoASAvJSS";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StartBrowser'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class StartBrowserParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:Tabs' using new browser instance
        /// </summary>
        public string UINowakartaInternetExpWindowUrl = "about:Tabs";
        
        /// <summary>
        /// Type 'http{RShiftKey}:/l{Back}//{Back}local' in text box
        /// </summary>
        public string UIItemEditSendKeys = "http{RShiftKey}:/l{Back}//{Back}local";
        
        /// <summary>
        /// Type 'host{RShiftKey}:63352' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "host{RShiftKey}:63352";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'BadLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class BadLoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "mOL/lXDUSd/hy7K5BZnJEA==";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINowakartaInternetExpWindow : BrowserWindow
    {
        
        public UINowakartaInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Nowa karta";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Nowa karta");
            this.WindowTitles.Add("localhost:63352/ - Bing");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIPasekadresuClient UIPasekadresuClient
        {
            get
            {
                if ((this.mUIPasekadresuClient == null))
                {
                    this.mUIPasekadresuClient = new UIPasekadresuClient(this);
                }
                return this.mUIPasekadresuClient;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIKontrolkastronyToolBar UIKontrolkastronyToolBar
        {
            get
            {
                if ((this.mUIKontrolkastronyToolBar == null))
                {
                    this.mUIKontrolkastronyToolBar = new UIKontrolkastronyToolBar(this);
                }
                return this.mUIKontrolkastronyToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIPasekadresuClient mUIPasekadresuClient;
        
        private UIItemWindow mUIItemWindow;
        
        private UIKontrolkastronyToolBar mUIKontrolkastronyToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPasekadresuClient : WinClient
    {
        
        public UIPasekadresuClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Pasek adresu";
            this.WindowTitles.Add("Nowa karta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAdresiwyszukiwaniezaEdit
        {
            get
            {
                if ((this.mUIAdresiwyszukiwaniezaEdit == null))
                {
                    this.mUIAdresiwyszukiwaniezaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAdresiwyszukiwaniezaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Adres i wyszukiwanie za pomocą Bing";
                    this.mUIAdresiwyszukiwaniezaEdit.WindowTitles.Add("Nowa karta");
                    #endregion
                }
                return this.mUIAdresiwyszukiwaniezaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAdresiwyszukiwaniezaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Adres i wyszukiwanie za pomocą Bing";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("Nowa karta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Nowa karta");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIKontrolkastronyToolBar : WinToolBar
    {
        
        public UIKontrolkastronyToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Kontrolka strony";
            this.WindowTitles.Add("Nowa karta");
            #endregion
        }
        
        #region Properties
        public WinButton UIPrzejdźdolocalhost63Button
        {
            get
            {
                if ((this.mUIPrzejdźdolocalhost63Button == null))
                {
                    this.mUIPrzejdźdolocalhost63Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIPrzejdźdolocalhost63Button.SearchProperties[WinButton.PropertyNames.Name] = "Przejdź do „localhost:63352” (Alt+Enter, aby otworzyć na nowej karcie)";
                    this.mUIPrzejdźdolocalhost63Button.WindowTitles.Add("Nowa karta");
                    #endregion
                }
                return this.mUIPrzejdźdolocalhost63Button;
            }
        }
        
        public WinButton UIPrzejdźdohttplocalhoButton
        {
            get
            {
                if ((this.mUIPrzejdźdohttplocalhoButton == null))
                {
                    this.mUIPrzejdźdohttplocalhoButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIPrzejdźdohttplocalhoButton.SearchProperties[WinButton.PropertyNames.Name] = "Przejdź do „http://localhost:63352/” (Alt+Enter, aby otworzyć na nowej karcie)";
                    this.mUIPrzejdźdohttplocalhoButton.WindowTitles.Add("Nowa karta");
                    #endregion
                }
                return this.mUIPrzejdźdohttplocalhoButton;
            }
        }
        
        public WinButton UIPrzejdźdolocalhost63Button1
        {
            get
            {
                if ((this.mUIPrzejdźdolocalhost63Button1 == null))
                {
                    this.mUIPrzejdźdolocalhost63Button1 = new WinButton(this);
                    #region Search Criteria
                    this.mUIPrzejdźdolocalhost63Button1.SearchProperties[WinButton.PropertyNames.Name] = "Przejdź do „localhost:63352/” (Alt+Enter, aby otworzyć na nowej karcie)";
                    this.mUIPrzejdźdolocalhost63Button1.WindowTitles.Add("Nowa karta");
                    #endregion
                }
                return this.mUIPrzejdźdolocalhost63Button1;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIPrzejdźdolocalhost63Button;
        
        private WinButton mUIPrzejdźdohttplocalhoButton;
        
        private WinButton mUIPrzejdźdolocalhost63Button1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Kontekst";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIKontekstMenu UIKontekstMenu
        {
            get
            {
                if ((this.mUIKontekstMenu == null))
                {
                    this.mUIKontekstMenu = new UIKontekstMenu(this);
                }
                return this.mUIKontekstMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIKontekstMenu mUIKontekstMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIKontekstMenu : WinMenu
    {
        
        public UIKontekstMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Kontekst";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIWklejMenuItem
        {
            get
            {
                if ((this.mUIWklejMenuItem == null))
                {
                    this.mUIWklejMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIWklejMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Wklej";
                    #endregion
                }
                return this.mUIWklejMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIWklejMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageProjectInterWindow : BrowserWindow
    {
        
        public UIHomePageProjectInterWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - Project";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - Project");
            this.WindowTitles.Add("Log in - Project");
            this.WindowTitles.Add("Index - Project");
            this.WindowTitles.Add("Create - Project");
            this.WindowTitles.Add("Details - Project");
            this.WindowTitles.Add("Delete - Project");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageProjectDocument UIHomePageProjectDocument
        {
            get
            {
                if ((this.mUIHomePageProjectDocument == null))
                {
                    this.mUIHomePageProjectDocument = new UIHomePageProjectDocument(this);
                }
                return this.mUIHomePageProjectDocument;
            }
        }
        
        public UILoginProjectDocument UILoginProjectDocument
        {
            get
            {
                if ((this.mUILoginProjectDocument == null))
                {
                    this.mUILoginProjectDocument = new UILoginProjectDocument(this);
                }
                return this.mUILoginProjectDocument;
            }
        }
        
        public UIIndexProjectDocument UIIndexProjectDocument
        {
            get
            {
                if ((this.mUIIndexProjectDocument == null))
                {
                    this.mUIIndexProjectDocument = new UIIndexProjectDocument(this);
                }
                return this.mUIIndexProjectDocument;
            }
        }
        
        public UICreateProjectDocument UICreateProjectDocument
        {
            get
            {
                if ((this.mUICreateProjectDocument == null))
                {
                    this.mUICreateProjectDocument = new UICreateProjectDocument(this);
                }
                return this.mUICreateProjectDocument;
            }
        }
        
        public UIIndexProjectDocument2 UIIndexProjectDocument2
        {
            get
            {
                if ((this.mUIIndexProjectDocument2 == null))
                {
                    this.mUIIndexProjectDocument2 = new UIIndexProjectDocument2(this);
                }
                return this.mUIIndexProjectDocument2;
            }
        }
        
        public UIIndexProjectDocument1 UIIndexProjectDocument1
        {
            get
            {
                if ((this.mUIIndexProjectDocument1 == null))
                {
                    this.mUIIndexProjectDocument1 = new UIIndexProjectDocument1(this);
                }
                return this.mUIIndexProjectDocument1;
            }
        }
        
        public UIIndexProjectDocument3 UIIndexProjectDocument3
        {
            get
            {
                if ((this.mUIIndexProjectDocument3 == null))
                {
                    this.mUIIndexProjectDocument3 = new UIIndexProjectDocument3(this);
                }
                return this.mUIIndexProjectDocument3;
            }
        }
        
        public UIDetailsProjectDocument UIDetailsProjectDocument
        {
            get
            {
                if ((this.mUIDetailsProjectDocument == null))
                {
                    this.mUIDetailsProjectDocument = new UIDetailsProjectDocument(this);
                }
                return this.mUIDetailsProjectDocument;
            }
        }
        
        public UIIndexProjectDocument11 UIIndexProjectDocument11
        {
            get
            {
                if ((this.mUIIndexProjectDocument11 == null))
                {
                    this.mUIIndexProjectDocument11 = new UIIndexProjectDocument11(this);
                }
                return this.mUIIndexProjectDocument11;
            }
        }
        
        public UIDeleteProjectDocument UIDeleteProjectDocument
        {
            get
            {
                if ((this.mUIDeleteProjectDocument == null))
                {
                    this.mUIDeleteProjectDocument = new UIDeleteProjectDocument(this);
                }
                return this.mUIDeleteProjectDocument;
            }
        }
        
        public UIDetailsProjectDocument1 UIDetailsProjectDocument1
        {
            get
            {
                if ((this.mUIDetailsProjectDocument1 == null))
                {
                    this.mUIDetailsProjectDocument1 = new UIDetailsProjectDocument1(this);
                }
                return this.mUIDetailsProjectDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageProjectDocument mUIHomePageProjectDocument;
        
        private UILoginProjectDocument mUILoginProjectDocument;
        
        private UIIndexProjectDocument mUIIndexProjectDocument;
        
        private UICreateProjectDocument mUICreateProjectDocument;
        
        private UIIndexProjectDocument2 mUIIndexProjectDocument2;
        
        private UIIndexProjectDocument1 mUIIndexProjectDocument1;
        
        private UIIndexProjectDocument3 mUIIndexProjectDocument3;
        
        private UIDetailsProjectDocument mUIDetailsProjectDocument;
        
        private UIIndexProjectDocument11 mUIIndexProjectDocument11;
        
        private UIDeleteProjectDocument mUIDeleteProjectDocument;
        
        private UIDetailsProjectDocument1 mUIDetailsProjectDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageProjectDocument : HtmlDocument
    {
        
        public UIHomePageProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/";
            this.WindowTitles.Add("Home Page - Project");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginLink";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"loginLink\" href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUILoginHyperlink.WindowTitles.Add("Home Page - Project");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public HtmlHyperlink UIBooksHyperlink
        {
            get
            {
                if ((this.mUIBooksHyperlink == null))
                {
                    this.mUIBooksHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBooksHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBooksHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBooksHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBooksHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Books";
                    this.mUIBooksHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books";
                    this.mUIBooksHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBooksHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books";
                    this.mUIBooksHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBooksHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Books\"";
                    this.mUIBooksHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIBooksHyperlink.WindowTitles.Add("Home Page - Project");
                    #endregion
                }
                return this.mUIBooksHyperlink;
            }
        }
        
        public UILogoutFormCustom UILogoutFormCustom
        {
            get
            {
                if ((this.mUILogoutFormCustom == null))
                {
                    this.mUILogoutFormCustom = new UILogoutFormCustom(this);
                }
                return this.mUILogoutFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILoginHyperlink;
        
        private HtmlHyperlink mUIBooksHyperlink;
        
        private UILogoutFormCustom mUILogoutFormCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogoutFormCustom : HtmlCustom
    {
        
        public UILogoutFormCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "logoutForm";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "navbar-right";
            this.FilterProperties["ControlDefinition"] = "class=\"navbar-right\" id=\"logoutForm\" act";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Home Page - Project");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILogoffHyperlink
        {
            get
            {
                if ((this.mUILogoffHyperlink == null))
                {
                    this.mUILogoffHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogoffHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILogoffHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogoffHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogoffHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log off";
                    this.mUILogoffHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "document.getElementById(\'logoutForm\').submit()";
                    this.mUILogoffHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogoffHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:document.getElementById(\'logoutForm\').submit()";
                    this.mUILogoffHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILogoffHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"javascript:document.getElementById";
                    this.mUILogoffHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUILogoffHyperlink.WindowTitles.Add("Home Page - Project");
                    #endregion
                }
                return this.mUILogoffHyperlink;
            }
        }
        
        public HtmlHyperlink UIHelloAdminHyperlink
        {
            get
            {
                if ((this.mUIHelloAdminHyperlink == null))
                {
                    this.mUIHelloAdminHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHelloAdminHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHelloAdminHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHelloAdminHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHelloAdminHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Hello Admin!";
                    this.mUIHelloAdminHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Manage";
                    this.mUIHelloAdminHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Manage";
                    this.mUIHelloAdminHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Account/Manage";
                    this.mUIHelloAdminHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHelloAdminHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Manage\" href=\"/Account/Manage\"";
                    this.mUIHelloAdminHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIHelloAdminHyperlink.WindowTitles.Add("Home Page - Project");
                    #endregion
                }
                return this.mUIHelloAdminHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILogoffHyperlink;
        
        private HtmlHyperlink mUIHelloAdminHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginProjectDocument : HtmlDocument
    {
        
        public UILoginProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Account/Login";
            this.WindowTitles.Add("Log in - Project");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "UserName";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User name";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Log in - Project");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Log in - Project");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public UILoginFormCustom UILoginFormCustom
        {
            get
            {
                if ((this.mUILoginFormCustom == null))
                {
                    this.mUILoginFormCustom = new UILoginFormCustom(this);
                }
                return this.mUILoginFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private UILoginFormCustom mUILoginFormCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginFormCustom : HtmlCustom
    {
        
        public UILoginFormCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "loginForm";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"loginForm\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Log in - Project");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log in";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUILoginButton.WindowTitles.Add("Log in - Project");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        
        public HtmlCustom UIInvalidusernameorpasCustom
        {
            get
            {
                if ((this.mUIInvalidusernameorpasCustom == null))
                {
                    this.mUIInvalidusernameorpasCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIInvalidusernameorpasCustom.SearchProperties["TagName"] = "LI";
                    this.mUIInvalidusernameorpasCustom.SearchProperties["Id"] = null;
                    this.mUIInvalidusernameorpasCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIInvalidusernameorpasCustom.FilterProperties["Class"] = null;
                    this.mUIInvalidusernameorpasCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIInvalidusernameorpasCustom.FilterProperties["InnerText"] = "Invalid username or password.";
                    this.mUIInvalidusernameorpasCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIInvalidusernameorpasCustom.WindowTitles.Add("Log in - Project");
                    #endregion
                }
                return this.mUIInvalidusernameorpasCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUILoginButton;
        
        private HtmlCustom mUIInvalidusernameorpasCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexProjectDocument : HtmlDocument
    {
        
        public UIIndexProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books";
            this.WindowTitles.Add("Index - Project");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "H2";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UICreateNewHyperlink
        {
            get
            {
                if ((this.mUICreateNewHyperlink == null))
                {
                    this.mUICreateNewHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Create New";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-success";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-success\" href=\"/Books/Cre";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUICreateNewHyperlink.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUICreateNewHyperlink;
            }
        }
        
        public HtmlComboBox UIBookGenreComboBox
        {
            get
            {
                if ((this.mUIBookGenreComboBox == null))
                {
                    this.mUIBookGenreComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIBookGenreComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "bookGenre";
                    this.mUIBookGenreComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "bookGenre";
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "3";
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"bookGenre\" id=\"bookGenre\"";
                    this.mUIBookGenreComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIBookGenreComboBox.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIBookGenreComboBox;
            }
        }
        
        public HtmlInputButton UIFilterButton
        {
            get
            {
                if ((this.mUIFilterButton == null))
                {
                    this.mUIFilterButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIFilterButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIFilterButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIFilterButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Filter";
                    this.mUIFilterButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIFilterButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIFilterButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIFilterButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIFilterButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUIFilterButton.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIFilterButton;
            }
        }
        
        public HtmlHyperlink UIItem3Hyperlink
        {
            get
            {
                if ((this.mUIItem3Hyperlink == null))
                {
                    this.mUIItem3Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem3Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem3Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem3Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem3Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "3";
                    this.mUIItem3Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books/Index/Page3";
                    this.mUIItem3Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem3Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books/Index/Page3";
                    this.mUIItem3Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIItem3Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Books/Index/Page3\"";
                    this.mUIItem3Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "19";
                    this.mUIItem3Hyperlink.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIItem3Hyperlink;
            }
        }
        
        public HtmlHyperlink UIDetailsHyperlink
        {
            get
            {
                if ((this.mUIDetailsHyperlink == null))
                {
                    this.mUIDetailsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Details";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books/Details/1";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books/Details/1";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = " btn btn-info";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\" btn btn-info\" href=\"/Books/Detai";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIDetailsHyperlink.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIDetailsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUICreateNewHyperlink;
        
        private HtmlComboBox mUIBookGenreComboBox;
        
        private HtmlInputButton mUIFilterButton;
        
        private HtmlHyperlink mUIItem3Hyperlink;
        
        private HtmlHyperlink mUIDetailsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateProjectDocument : HtmlDocument
    {
        
        public UICreateProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Create - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Create";
            this.WindowTitles.Add("Create - Project");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UITitleEdit
        {
            get
            {
                if ((this.mUITitleEdit == null))
                {
                    this.mUITitleEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITitleEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Title";
                    this.mUITitleEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Title";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Title";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Title\" class=\"text-box single-line";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUITitleEdit.WindowTitles.Add("Create - Project");
                    #endregion
                }
                return this.mUITitleEdit;
            }
        }
        
        public HtmlEdit UIReleaseDateEdit
        {
            get
            {
                if ((this.mUIReleaseDateEdit == null))
                {
                    this.mUIReleaseDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIReleaseDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ReleaseDate";
                    this.mUIReleaseDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ReleaseDate";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Release Date";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ReleaseDate\" class=\"text-box singl";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIReleaseDateEdit.WindowTitles.Add("Create - Project");
                    #endregion
                }
                return this.mUIReleaseDateEdit;
            }
        }
        
        public HtmlEdit UIGenreEdit
        {
            get
            {
                if ((this.mUIGenreEdit == null))
                {
                    this.mUIGenreEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIGenreEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Genre";
                    this.mUIGenreEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Genre";
                    this.mUIGenreEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Genre";
                    this.mUIGenreEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIGenreEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIGenreEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIGenreEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Genre\" class=\"text-box single-line";
                    this.mUIGenreEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIGenreEdit.WindowTitles.Add("Create - Project");
                    #endregion
                }
                return this.mUIGenreEdit;
            }
        }
        
        public HtmlInputButton UICreateButton
        {
            get
            {
                if ((this.mUICreateButton == null))
                {
                    this.mUICreateButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Create";
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-success";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-success\" type=\"submit\" va";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUICreateButton.WindowTitles.Add("Create - Project");
                    #endregion
                }
                return this.mUICreateButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUITitleEdit;
        
        private HtmlEdit mUIReleaseDateEdit;
        
        private HtmlEdit mUIGenreEdit;
        
        private HtmlInputButton mUICreateButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexProjectDocument2 : HtmlDocument
    {
        
        public UIIndexProjectDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books?bookGenre=Thriller";
            this.WindowTitles.Add("Index - Project");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem2Hyperlink
        {
            get
            {
                if ((this.mUIItem2Hyperlink == null))
                {
                    this.mUIItem2Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "2";
                    this.mUIItem2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books/Index/Page2";
                    this.mUIItem2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books/Index/Page2?currentFilter=Thriller";
                    this.mUIItem2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIItem2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Books/Index/Page2?currentFilter=T";
                    this.mUIItem2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "18";
                    this.mUIItem2Hyperlink.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIItem2Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem2Hyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexProjectDocument1 : HtmlDocument
    {
        
        public UIIndexProjectDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Index/Page2";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Index/Page2?currentFilter=Thriller";
            this.WindowTitles.Add("Index - Project");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Title \r\n\r\nRelease Date \r\n\r\nGenre \r\n\r\nAut";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "5";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Index - Project");
            #endregion
        }
        
        #region Properties
        public HtmlCell UINewCell
        {
            get
            {
                if ((this.mUINewCell == null))
                {
                    this.mUINewCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUINewCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUINewCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUINewCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUINewCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "New ";
                    this.mUINewCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUINewCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUINewCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUINewCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUINewCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUINewCell.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUINewCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUINewCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexProjectDocument3 : HtmlDocument
    {
        
        public UIIndexProjectDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Index/Page2";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Index/Page2";
            this.WindowTitles.Add("Index - Project");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDetailsHyperlink
        {
            get
            {
                if ((this.mUIDetailsHyperlink == null))
                {
                    this.mUIDetailsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Details";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books/Details/5";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books/Details/5";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = " btn btn-info";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\" btn btn-info\" href=\"/Books/Detai";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "9";
                    this.mUIDetailsHyperlink.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIDetailsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDetailsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDetailsProjectDocument : HtmlDocument
    {
        
        public UIDetailsProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Details - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Details/5";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Details/5";
            this.WindowTitles.Add("Details - Project");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIWhereSheWentCustom
        {
            get
            {
                if ((this.mUIWhereSheWentCustom == null))
                {
                    this.mUIWhereSheWentCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIWhereSheWentCustom.SearchProperties["TagName"] = "DD";
                    this.mUIWhereSheWentCustom.SearchProperties["Id"] = null;
                    this.mUIWhereSheWentCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIWhereSheWentCustom.FilterProperties["Class"] = null;
                    this.mUIWhereSheWentCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIWhereSheWentCustom.FilterProperties["InnerText"] = "Where She Went ";
                    this.mUIWhereSheWentCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIWhereSheWentCustom.WindowTitles.Add("Details - Project");
                    #endregion
                }
                return this.mUIWhereSheWentCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIWhereSheWentCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexProjectDocument11 : HtmlDocument
    {
        
        public UIIndexProjectDocument11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Index/Page3";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Index/Page3";
            this.WindowTitles.Add("Index - Project");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDeleteHyperlink
        {
            get
            {
                if ((this.mUIDeleteHyperlink == null))
                {
                    this.mUIDeleteHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Delete";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Books/Delete/26";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:63352/Books/Delete/26";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = " btn btn-danger";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\" btn btn-danger\" href=\"/Books/Del";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "16";
                    this.mUIDeleteHyperlink.WindowTitles.Add("Index - Project");
                    #endregion
                }
                return this.mUIDeleteHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDeleteHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDeleteProjectDocument : HtmlDocument
    {
        
        public UIDeleteProjectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Delete - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Delete/26";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Delete/26";
            this.WindowTitles.Add("Delete - Project");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "H2";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Delete - Project");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDetailsProjectDocument1 : HtmlDocument
    {
        
        public UIDetailsProjectDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Details - Project";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Details/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:63352/Books/Details/1";
            this.WindowTitles.Add("Details - Project");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UITheDaVinciCodeCustom
        {
            get
            {
                if ((this.mUITheDaVinciCodeCustom == null))
                {
                    this.mUITheDaVinciCodeCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUITheDaVinciCodeCustom.SearchProperties["TagName"] = "DD";
                    this.mUITheDaVinciCodeCustom.SearchProperties["Id"] = null;
                    this.mUITheDaVinciCodeCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUITheDaVinciCodeCustom.FilterProperties["Class"] = null;
                    this.mUITheDaVinciCodeCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUITheDaVinciCodeCustom.FilterProperties["InnerText"] = "The Da Vinci Code ";
                    this.mUITheDaVinciCodeCustom.FilterProperties["TagInstance"] = "1";
                    this.mUITheDaVinciCodeCustom.WindowTitles.Add("Details - Project");
                    #endregion
                }
                return this.mUITheDaVinciCodeCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUITheDaVinciCodeCustom;
        #endregion
    }
}
